* tree
** Description
https://oj.thusaac.org/#!/contest/23/problem/123

** Solution
这题主要就是树链剖分的一个扩展: 询问/修改与一条链相邻的点.

然后发现, 这个可以通过魔改树链剖分的那些边在线段树里的顺序来解决.

考虑这样一种方案:
在最开头的肯定是根连下去的一条重链, 紧接着, 我们将这条重链从下到上经过的点连出去的虚边依次加入, 最后, 再按顺序 dfs 这些虚边的子树.

容易发现, 按照这样的顺序, 链和子树依旧是可以查询/修改的.
同时还可以支持链相邻的查询/修改.

* count
** Description
https://oj.thusaac.org/#!/contest/23/problem/126

** Solution
这题挺厉害的.
不过题面写错了, 要求的应该是
$$\prod_{i=1}^n A_i^{d_i} d_i$$

首先用 Prufer 编码发现要求的就是
\begin{align*}
ans &= \sum_{d_1 + \cdots + d_n = n - 2} (n-2)! \prod_{i=1}^n \frac{1}{d_i!} A_i^{d_i + 1} (d_i + 1) \\
    &= \left((n-2)! \prod_{i=1}^n A_i\right) \sum_{d_1 + \cdots + d_n = n - 2} \prod_{i=1}^n \frac{1}{d_i!} A_i^{d_i} (d_i + 1) \\
\end{align*}

也就是要求
$$\sum_{d_1 + \cdots + d_n = n - 2} \prod_{i=1}^n \frac{1}{d_i!} A_i^{d_i} (d_i + 1)$$

这个已经可以 $O(n^3)$ 做了.
用 FFT 可以做到 $O(n^2 \log n)$.

然后, 考虑每一个形如 $d_{p_1} d_{p_2} ... d_{p_k}$ 的单项式

\begin{align*}
 & d_{p_1} d_{p_2} ... d_{p_k} \sum_{d_1 + \cdots + d_n = n - 2} \prod_{i=1}^n \frac{1}{d_i!} A_i^{d_i} \\
=& \left( \prod_{i=1}^k A_{p_i} \right) \sum_{d_1 + \cdots + d_n = n - 2} \prod_{i=1}^{n} \frac{1}{(d_i - [i \in \mathcal{P}])!} A_i^{d_i - [i \in \mathcal{P}]} \\
=& \left( \prod_{i=1}^k A_{p_i} \right) \sum_{d_1 + \cdots + d_n = n - 2 - k} \prod_{i=1}^{n} \frac{1}{d_i!} A_i^{d_i} \\
=& \left( \prod_{i=1}^k A_{p_i} \right) \frac{(\sum_{i=1}^n A_i)^{n - 2 - k}}{(n - 2 - k)!}
\end{align*}

($\mathcal{P} = \{ p_1, p_2, ..., p_k\}$)

精彩!
然后就可以 $O(n^2)$ DP 了.

可以发现, 如果要求的是
$$\sum_{d_1 + \cdots + d_n = n - 2} \prod_{i=1}^n \frac{1}{d_i!} A_i^{d_i} d_i$$

反而是不好做的. 
至少我现在不会...
